version: v1

labels:
  - label: kind/feature
    sync: true
    matcher:
      title: "^feat\\(.+\\): .+"

  - label: kind/feature
    sync: true
    matcher:
      title: "^feature\\(.+\\): .+"

  - label: kind/fix
    sync: true
    matcher:
      title: "^fix\\(.+\\): .+"

  - label: kind/chore
    sync: true
    matcher:
      title: "^chore\\(.+\\): .+"

  - label: kind/refactor
    sync: true
    matcher:
      title: "^refactor\\(.+\\): .+"

  - label: kind/docs
    sync: true
    matcher:
      title: "^docs\\(.+\\): .+"

  - label: kind/dependencies
    sync: true
    matcher:
      title: "^bump(\\(.+\\))?: .+"

  - label: area/workflow
    sync: true
    matcher:
      files: ".github/**"

  - label: area/sticky-jest
    sync: true
    matcher:
      files: "packages/sticky-jest/**"

  - label: area/sticky-prettier
    sync: true
    matcher:
      files: "packages/sticky-prettier/**"

  - label: area/sticky-turbo
    sync: true
    matcher:
      files: "packages/sticky-turbo/**"

  - label: area/sticky-turbo-jest
    sync: true
    matcher:
      files: "packages/sticky-turbo-jest/**"

  - label: area/sticky-typescript
    sync: true
    matcher:
      files: "packages/sticky-typescript/**"

  - label: area/eslint-config
    sync: true
    matcher:
      files: "packages/eslint-config/**"

checks:
  - context: "Semantic Pull Request"
    description:
      success: Ready for review & merge.
      failure: "Missing semantic title or label for merge [kind(directory): title]"
    labels:
      any:
        - kind/feature
        - kind/fix
        - kind/chore
        - kind/refactor
        - kind/docs
        - kind/dependencies
